In [1]:
import numpy as np  # task 1


In [2]:
# task 2

array = np.array([1, 2, 3, 4, 5])  # массив из списка
zeros_array = np.zeros((2, 3))  # массив нулец
ones_array = np.ones((2, 3))  # массив единиц
arange_array = np.arange(0, 10, 2)  # массив создается как range

array, zeros_array, ones_array, arange_array

(array([1, 2, 3, 4, 5]),
 array([[0., 0., 0.],
        [0., 0., 0.]]),
 array([[1., 1., 1.],
        [1., 1., 1.]]),
 array([0, 2, 4, 6, 8]))

In [3]:
# task 3

print("ones_array stats:", ones_array.shape, ones_array.dtype)  # размерность и тип

ones_array stats: (2, 3) float64


In [4]:
# task 4

element = array[2]  # третий элемент
print(arange_array)
subarray = arange_array[1:4]  # элементы со второго по тертий включительно

element, subarray

[0 2 4 6 8]


(np.int64(3), array([2, 4, 6]))

In [5]:
# task 5

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

sum_array = a + b  # сложение элементов
mul_array = a * b  # умножение

mean = a.mean()  # средний в массиве

sum_array, mul_array, mean

(array([5, 7, 9]), array([ 4, 10, 18]), np.float64(2.0))